### ISSUE TITLE
Mangafox not working (again)

### ISSUE THREAD

**Issue by Mereck13579** [Deathspike/mangarack#75]
Mangarack works normally when there's nothing to download. Otherwise crashes after a few seconds : 
[Testing with http://mangafox.me/manga/tsugumomo/]
Fetching Tsugumomo
Fetching Tsugumomo V19 #102.cbz
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/usr/lib/node_modules/mangarack/dist/..\mangarack-node-core\src\services\httpService.ts:125:31)
    at self.callback (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:188:1)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.init (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:276:1)
    at new Request (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:130:1)
    at request (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/index.js:54:1)
    at /usr/lib/node_modules/mangarack/dist/..\mangarack-node-core\src\services\httpService.ts:114:5
    at /usr/lib/node_modules/mangarack/dist/..\mangarack-node-core\src\services\httpService.ts:110:10
    at step (/usr/lib/node_modules/mangarack/mangarack-component-core/node_modules/tslib/tslib.js:122:1)

**Comment by Deathspike** [comment]
Looks like MangaFox switched to HTTPS.  I will need to update the code to support this.

Perhaps rewrite current addresses from HTTP to HTTPS...

**Comment by usergood** [comment]
The issue seems to be that MangaFox has changed their href tags to start with //mangafox.me, 
se the address being used is //mangafox.me/manga/tsugumomo/v01/c001.1html  and such.
I just made a quick and ugly fix i my cli.js att row 8842:

`if(address.startsWith('//')) {
      address = 'http:'+address;
}`

It is ugly, and completly wrong, but just to validate the bug. And make it possible to run the cli for now.

**Comment by Mereck13579** [comment]
@usergood nice one, your workaround is working here as well.

**Comment by Deathspike** [comment]
I've just pushed `4.2.2` with the 'official' changes:

* Fixed an issue in `httpService` causing an error when doing error-reporting.
* Fixed an issue with relative URLs (thanks @usergood for the problem analysis) in the `mangafox` core.
* Switched `mangafox` over to *HTTPS*. URLs with `https://` are now supported too.

It would be great if you could let me know how this change works out :-)

**Comment by Mereck13579** [comment]
Updated mangarack, https is working for me now, mangafox is back. Thanks!
(though I'll have to open another issue now that I noticed another thing being wrong...)

**Comment by usergood** [comment]
@Deathspike the changes works fine for me, both https and http.
Nice solution with the site resolve, proberly the best solution for now, since it can be a bit messy to get a context aware http client. At least when you are doing batches of fetches for multiple series.
So good work, and that was fast!

**Comment by Deathspike** [comment]
Indeed. A context-aware client is something I want to do in the mid-to-long term, but breaking it all open right now is a bit too much. Thanks guys!
