### ISSUE TITLE
[5.0] Phase 01 Feedback

### ISSUE THREAD

**Issue by Deathspike** [Deathspike/mangarack#81]
## Introduction

https://github.com/Deathspike/mangarack/tree/next

## Installation

Run in your terminal or command-line:

    npm install -g mangarack@next

## Usage

Add one or more series:

    mangarack-cli create http://mangafox.la/manga/futari_dake/

Whenever you want to download chapters for all added series:

    mangarack-cli download

The chapters will be downloaded to:

* Windows: `C:\Users\<YOURNAME>\mangarack`
* MacOS: `/Users/<YOURNAME>/mangarack`

## Revert to 4.0

Run in your terminal or command-line:

    npm install -g mangarack

## Feedback

This is a feedback thread. All feedback is appreciated.

**Comment by XellossMetallium** [comment]
Awesome! I'm not at home right now. Hopefully I'll be able to test and report in no less than 4 day. :)
-------- Messaggio originale --------Da: Roel van Uden <notifications@github.com> Data: 27/01/18  11:50  (GMT+01:00) A: Deathspike/mangarack <mangarack@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Oggetto: [Deathspike/mangarack] [5.0] Phase 01 Feedback (#81) 
Introduction
https://github.com/Deathspike/mangarack/tree/next
Installation
Run in your terminal or command-line:
npm install -g mangarack@next

Usage
Add one or more series:
mangarack-cli create http://mangafox.la/manga/futari_dake/

Whenever you want to download chapters for all added series:
mangarack-cli download

The chapters will be downloaded to:

Windows: C:\Users\<YOURNAME>\mangarack
MacOS: /Users/<YOURNAME>/mangarack

Revert to 4.0
Run in your terminal or command-line:
npm install -g mangarack

Feedback
This is a feedback thread. All feedback is appreciated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Deathspike/mangarack","title":"Deathspike/mangarack","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Deathspike/mangarack"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"[5.0] Phase 01 Feedback (#81)"}],"action":{"name":"View Issue","url":"https://github.com/Deathspike/mangarack/issues/81"}}}

**Comment by Deathspike** [comment]
Awesome! Much appreciated @XellossMetallium

**Comment by usergood** [comment]
It looks good so far, I like the idea with a "central" repository of "watched" series instead of the old text-file.
And it seem to be able to handle a couple more chapters before the timeout happens, like it do a lot on mangafax sinche their update in the old client.

Some thoughts though, you should add "download/manga" directory to mangafox.json instead of hardcoded default. So we can get the option to change or location of our manga library.
(in the future this should also be possible on series level is my recomendation.)

And i like the Phase scedule you have layed out.
I would personaly like to have the following features planned or added as well:
 comicinfo.xml back with frontcover and a more updated comicrack structure. (I use it to export my manga to my kindle)
And the possibility to maybe choose to store archives on volume instead of chapters (just something i have to do manually today with comicrack)

But i like your work, and hope you can keep up your phase scedule!

**Comment by Deathspike** [comment]
Thanks for the feedback! Could you elaborate on the following:

> more updated comicrack structure

And:

> And the possibility to maybe choose to store archives on volume instead of chapters (just something i have to do manually today with comicrack)

**Comment by XellossMetallium** [comment]
> And the possibility to maybe choose to store archives on volume instead of chapters (just something i have to do manually today with comicrack)

I suppose he suggests to have the chapters that also have the volume tag (i.e. "vol 2 chapter 8" in the late Batoto, or under "Volume 07 Chapter 21 - 27" in Mangafox) optionally compressed in a single cbz, so by volume and not by chapter. 
It would be nice, if not for the issues that could arise in the case something changes within a single chapter, since mangarack would be forced to recreate and recompress the whole volume each time. 

Another option could be to act on the client side (the future apps): there the chapters could be grouped by volume (i.e. by showing the single volume with a "READ" button, but also a "+" icon to show the separate chapters) keeping them separated on the server side. 
Actually this could work well with something that I and someone else suggested some months ago: to scrape the proper cover for each volume from a provider that keeps them separated and properly tagged, like https://mcd.iosphe.re/
The result would be neat.

That being said, I suppose this is a matter for the "far" future.

For now I have an issue with 5.0. I can add the series, but the download wont start. I get the "Awaiting" message, then the process is completed without anything downloaded. 
I did a fresh installation of node, npm, graphicsmagik and mangarack@next on a different pc, by the way. Maybe I'm forgetting something.

**Comment by Deathspike** [comment]
I'm adding the suggestions :-)

In regard to the awaiting, that's probably because it's been fed a wrong URL..
It still requires mangafox URLS with trailing slash. Phase2 will switch to fanfox.net.

**Comment by Deathspike** [comment]
See https://github.com/Deathspike/mangarack/issues/83
